### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE] when running the example

### ISSUE THREAD

**Issue by obviyus** [jonahsnider/benchmark#204]
Hey, I'm trying to run [the example](https://github.com/jonahsnider/benchmark/blob/main/examples/basic/index.ts) from the readme but I keep getting:

```bash
RangeError [ERR_OUT_OF_RANGE]: The value of "val" is out of range. It must be a safe integer greater than 0. Received 0
    at new NodeError (node:internal/errors:387:5)
    at RecordableHistogram.record (node:internal/histogram:291:13)
    at processComplete (node:internal/perf/timerify:40:15)
    at Test.timerified  (node:internal/perf/timerify:87:5)
    at Test.run (file:///code/node_modules/@jonahsnider/benchmark/src/test.ts:57:30)
    at Suite.#runTestsOnce (file:///code/node_modules/@jonahsnider/benchmark/src/suite.ts:274:15)
    at Suite.#runTestsWithOptions (file:///code/node_modules/@jonahsnider/benchmark/src/suite.ts:286:29)
    at async Suite.#runWarmup (file:///code/node_modules/@jonahsnider/benchmark/src/suite.ts:307:3)
    at async Suite.run (file:///code/node_modules/@jonahsnider/benchmark/src/suite.ts:256:3)
    at async Benchmark.runSuites (file:///code/node_modules/@jonahsnider/benchmark/src/benchmark.ts:133:25) {
  code: 'ERR_OUT_OF_RANGE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Please let me know if there's something I'm missing!

**Comment by jonahsnider** [comment]
This is a bug with Node.js: https://github.com/nodejs/node/issues/41641
